version: '3'
services: 
  dockerappmayur:
    build: .
    ports: 
      - "5000:5000"
    depends_on: 
      - redis
    networks: 
      - my_net
  redis:
    image: redis:latest
    networks: 
      - my_net
networks: 
  my_net:
    driver: bridge